openapi: 3.1.0
info:
  title: Notion GPT Proxy
  description: A proxy API that allows ChatGPT to access Notion via a secure integration.
  version: 1.0.0

servers:
  - url: https://notion-plugin-proxy.onrender.com

paths:
  /notion/databases:
    get:
      operationId: listDatabases
      summary: List Notion databases
      responses:
        '200':
          description: A list of databases
          content:
            application/json:
              schema:
                type: object

  /notion/databases/{database_id}/query:
    post:
      operationId: queryDatabase
      summary: Query a specific database
      parameters:
        - name: database_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Query results
          content:
            application/json:
              schema:
                type: object

components: {}
//Add OpenAPI spec for Notion GPT proxy
