openapi: 3.1.0
info:
  title: Notion GPT Proxy
  description: API for GPT to interact with Notion data via a secure proxy
  version: 1.0.0

servers:
  - url: https://notion-plugin-proxy.onrender.com

paths:
  /notion/databases:
    get:
      operationId: listDatabases
      summary: Search all Notion databases
      description: Uses the /v1/search endpoint to return databases in the workspace.
      responses:
        '200':
          description: A list of Notion databases
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object

  /notion/databases/{database_id}/query:
    post:
      operationId: queryDatabase
      summary: Query a Notion database
      parameters:
        - name: database_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filter:
                  type: object
                sorts:
                  type: array
                  items:
                    type: object
                    properties:
                      property:
                        type: string
                      direction:
                        type: string
                        enum: [ascending, descending]
      responses:
        '200':
          description: Query results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object

components:
  schemas: {}
